### PR TITLE
Update odd+even.py

### PR DESCRIPTION
**Pull request by karentest01**
Updated on 12/1 2:01pm

### CODE REVIEW

**Comment by karen366** [comment]
karen, you did a good job!

**Comment by karentest01** [comment]
Thank you professor.

**Comment by karen366** [comment]
you are welcome.

**Comment by karen366** [comment]
You are welcome.

**Comment by karen366** [comment]
Lets try just comment

**Comment by karen366** [comment]
Let's try reopen.

**Pull request closed without merging**
